import type { Metadata } from "next";
import { ThemeProvider } from "next-themes";
import { Plus_Jakarta_Sans } from "next/font/google";
import ThemeWrapper from "./components/ThemeWrapper";
import { PanelProvider } from "./contexts/PanelProvider";
import SidebarProvider from "./contexts/SidebarProvider";
import "./globals.scss";
import { TaskDataProvider } from "./contexts/TskDataProvider";

const plus_jakarta_sans = Plus_Jakarta_Sans({
  subsets: ["latin"],
  weight: ["500", "700"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={plus_jakarta_sans.className}>
        <ThemeProvider>
          <PanelProvider>
            <SidebarProvider>
              <TaskDataProvider>
                <ThemeWrapper>{children}</ThemeWrapper>
              </TaskDataProvider>
            </SidebarProvider>
          </PanelProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
